#!/bin/bash

docker inspect $IMAGE_NAME | python -c 'import sys, json; env = json.load(sys.stdin)[0]["ContainerConfig"]["Env"]; print "\n".join( "export ENV_" + x for x in env)' > vars
source vars

docker tag $IMAGE_NAME $DOCKER_REPO:$ENV_SCAMPDB_VER-js$ENV_SCAMPJS_VER
docker push $DOCKER_REPO:$ENV_SCAMPDB_VER-js$ENV_SCAMPJS_VER